language: elixir
matrix:
  include:
    - os: linux
      otp_release: 21.0
      elixir: 1.7
    - os: osx
      language: generic
before_script:
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew update && brew install elixir; fi
script:
  - mix local.rebar --force
  - mix local.hex --force
  - mix deps.get
  - MIX_ENV=prod mix release --executable --transient
  - >
    if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then
    mkdir -p artifacts/darwin-amd64 && mv _build/prod/rel/toby/bin/toby.run artifacts/darwin-amd64/toby;
    fi
  - >
    if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then
    mkdir -p artifacts/linux-amd64 && mv _build/prod/rel/toby/bin/toby.run artifacts/linux-amd64/toby;
    fi
deploy:
  provider: releases
  api_key: $GITHUB_OAUTH_TOKEN
  file_glob: true
  file: artifacts/**/*
  skip_cleanup: true
  draft: true
